# implicitly 
line_length: 250

disabled_rules:
  - large_tuple
  - cyclomatic_complexity
  - function_body_length
  - file_length
  - type_body_length
  - identifier_name
  - type_name
  
identifier_name:
    excluded: ["id"]
